# See: https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#configuration-options-for-dependabotyml
version: 2

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: npm
    directory: '/interfaces/AW-App'
    schedule:
      interval: weekly
      day: tuesday
    open-pull-requests-limit: 3
    versioning-strategy: increase
    ignore:
      # Dependencies below are ordered alphabetically!
      # Most/all Angular-related dependencies are ignored for all versions
      - dependency-name: '@angular/*'
      - dependency-name: '@angular-devkit/*'
      - dependency-name: '@ionic/angular'
        update-types: ['version-update:semver-major']
      - dependency-name: '@ionic/cli'
        update-types: ['version-update:semver-major', 'version-update:semver-patch']
      - dependency-name: '@ionic/storage'
        versions: ['>= 2.3.0']
      - dependency-name: '@ngx-translate/core'
        versions: ['>= 14.0.0']
      - dependency-name: '@ngx-translate/http-loader'
        versions: ['>= 7.0.0']
      - dependency-name: '@swimlane/ngx-charts'
        versions: ['>= 15.0.0']
      - dependency-name: '@swimlane/ngx-datatable'
        versions: ['>= 18.0.0']
      - dependency-name: '@types/node'
        update-types: ['version-update:semver-major', 'version-update:semver-patch']
      - dependency-name: codelyzer
      - dependency-name: core-js
      - dependency-name: karma
      - dependency-name: ngx-popperjs
        versions: ['>= 13.0.0']
      - dependency-name: tslib
      - dependency-name: tslint
      - dependency-name: typescript
      - dependency-name: rxjs
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: 'zone.js'

  - package-ecosystem: npm
    directory: '/interfaces/HO-Portal'
    schedule:
      interval: weekly
      day: tuesday
    open-pull-requests-limit: 3
    versioning-strategy: increase
    ignore:
      # Dependencies below are ordered alphabetically!
      # Most/all Angular-related dependencies are ignored for all versions
      - dependency-name: '@angular/*'
      - dependency-name: '@angular-devkit/*'
      - dependency-name: '@ionic/angular'
        update-types: ['version-update:semver-major']
      - dependency-name: '@ionic/cli'
        update-types: ['version-update:semver-major', 'version-update:semver-patch']
      - dependency-name: '@ngx-translate/core'
        versions: ['>= 14.0.0']
      - dependency-name: '@ngx-translate/http-loader'
        versions: ['>= 7.0.0']
      - dependency-name: '@swimlane/ngx-charts'
        versions: ['>= 15.0.0']
      - dependency-name: '@swimlane/ngx-datatable'
        versions: ['>= 18.0.0']
      - dependency-name: '@types/node'
        update-types: ['version-update:semver-major', 'version-update:semver-patch']
      - dependency-name: codelyzer
      - dependency-name: core-js
      - dependency-name: karma
      - dependency-name: ngx-popperjs
        versions: ['>= 13.0.0']
      - dependency-name: tslib
      - dependency-name: tslint
      - dependency-name: typescript
      - dependency-name: rxjs
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: 'zone.js'

  - package-ecosystem: npm
    directory: '/interfaces/PA-App'
    schedule:
      interval: weekly
      day: tuesday
    open-pull-requests-limit: 3
    versioning-strategy: increase
    ignore:
      # Dependencies below are ordered alphabetically!
      # Most/all Angular-related dependencies are ignored for all versions
      - dependency-name: '@angular/*'
      - dependency-name: '@angular-devkit/*'
      - dependency-name: '@ionic/angular'
        update-types: ['version-update:semver-major']
      - dependency-name: '@ionic/cli'
        update-types: ['version-update:semver-major', 'version-update:semver-patch']
      - dependency-name: '@ngx-translate/core'
        versions: ['>= 14.0.0']
      - dependency-name: '@ngx-translate/http-loader'
        versions: ['>= 7.0.0']
      - dependency-name: '@swimlane/ngx-charts'
        versions: ['>= 15.0.0']
      - dependency-name: '@swimlane/ngx-datatable'
        versions: ['>= 18.0.0']
      - dependency-name: '@types/node'
        update-types: ['version-update:semver-major', 'version-update:semver-patch']
      - dependency-name: codelyzer
      - dependency-name: core-js
      - dependency-name: karma
      - dependency-name: ngx-popperjs
        versions: ['>= 13.0.0']
      - dependency-name: ngx-translate-lint
        versions: ['>= 1.14.0']
      - dependency-name: tslib
      - dependency-name: tslint
      - dependency-name: typescript
      - dependency-name: rxjs
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: 'zone.js'

  - package-ecosystem: npm
    directory: '/interfaces/tests'
    schedule:
      interval: weekly
      day: tuesday
    versioning-strategy: increase
    allow:
      - dependency-name: cypress
        update-types: ['version-update:semver-patch']

