# The settings from this file will override the values from `docker-compose.yml`
# When run via:
#     docker compose -f docker-compose.yml -f docker-compose.development.yml

# For use on macOS:
# See: https://www.docker.com/blog/user-guided-caching-in-docker-for-mac/
# To speed up the start-up process, use: ':cached' flag on volume definitions

# For debugging:
#
# Make the service boot and wait:
#     command: "tail -f /dev/null"
#

services:
  121db:
    image: 'postgres:14'
    init: true
    container_name: 121db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DBNAME}
    volumes:
      - './postgresql.conf:/etc/postgresql.conf'
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
    ports:
      - '5438:5432'
    restart: unless-stopped
    networks:
      pool_network:
        ipv4_address: 11.0.0.6
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DBNAME}'",
        ]
      interval: 10s
      timeout: 3s
      retries: 3

  121-service:
    build:
      target: development
    networks:
      pool_network:
        ipv4_address: 11.0.0.7
    volumes:
      - '121_service_node_modules:/home/node/app/node_modules'
      - './121-service:/home/node/app'

  twilio-mock-service:
    build:
      context: twilio-mock-service
      target: development
    init: true
    container_name: twilio-mock-service
    env_file:
      - .env
    environment:
      - GLOBAL_121_VERSION
    ports:
      - '3001:3001'
    stdin_open: true
    tty: true
    restart: on-failure
    networks:
      pool_network:
        ipv4_address: 11.0.0.8
    volumes:
      - 'twilio_mock_service_node_modules:/home/node/app/node_modules'
      - './twilio-mock-service:/home/node/app'

  121-redis:
    # Version 4.0.x & 6.0.x are supported by Azure Cache for Redis
    image: 'redis:6.0-alpine'
    ports:
      - '6379:6379'

volumes:
  121_service_node_modules:
  twilio_mock_service_node_modules:

networks:
  pool_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 11.0.0.0/24
