services:

  121-service:
    build:
      context: 121-service
      target: production
    init: true
    container_name: 121-service
    env_file:
      - .env
    environment:
      - GLOBAL_121_VERSION
    ports:
      - '${PORT_121_SERVICE}:${PORT_121_SERVICE}'
    stdin_open: true
    tty: true
    restart: on-failure
    healthcheck:
      test: curl --fail http://localhost:3000/api/health/health || exit 1
      interval: 2s
      retries: 10
      start_period: 10s
      timeout: 10s
