services:

  121-service:
    build:
      context: 121-service
      target: production
    init: true
    container_name: 121-service
    env_file:
      - .env
    environment:
      - GLOBAL_121_VERSION
    ports:
      - '${PORT_121_SERVICE}:${PORT_121_SERVICE}'
    stdin_open: true
    tty: true
    restart: on-failure
