# The settings from this file will override the values from `docker-compose.yml`

services:
  121db:
    image: 'postgres:14'
    init: true
    container_name: 121db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DBNAME}
    volumes:
      - './postgresql.conf:/etc/postgresql.conf'
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
    ports:
      - '5438:5432'
    restart: unless-stopped
    networks:
      pool_network:
        ipv4_address: 11.0.0.6
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DBNAME}'",
        ]
      interval: 10s
      timeout: 3s
      retries: 3

  121-service:
    networks:
      pool_network:
        ipv4_address: 11.0.0.7

  twilio-mock-service:
    build:
      context: twilio-mock-service
      target: production
    init: true
    container_name: twilio-mock-service
    env_file:
      - .env
    environment:
      - GLOBAL_121_VERSION
    ports:
      - '3001:3001'
    stdin_open: true
    tty: true
    restart: on-failure
    networks:
      pool_network:
        ipv4_address: 11.0.0.8
    healthcheck:
      test: curl --fail http://localhost:3001/api/lookups/phonenumbers || exit 1
      interval: 3s
      retries: 10
      start_period: 30s
      timeout: 10s
      
  121-redis:
    # Version 4.0.x & 6.0.x are supported by Azure Cache for Redis
    image: 'redis:6.0-alpine'
    ports:
      - '6379:6379'

networks:
  pool_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 11.0.0.0/24

