# More information on Static Web App workflow configurations,
# See: https://aka.ms/swaworkflowconfig
# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: 'Deploy [staging] Interface: Portal'

env:
  workingDirectory: interfaces/HO-Portal

permissions:
  actions: read
  pull-requests: write

on:
  workflow_dispatch:
  push:
    branches:
      - release/*
    paths:
      - '!.github/**'
      - '.github/workflows/deploy_staging_portal.yml'
      - 'interfaces/HO-Portal/**'
      - '**/.vscode/*'
      - '!*.md'
      - '!*.yml'

jobs:
  variables_workaround:
    runs-on: ubuntu-latest
    steps: [run: echo]
    outputs:
      workingDirectory: ${{ env.workingDirectory }}

  build:
    name: Build
    needs: variables_workaround
    uses: ./.github/workflows/_build_interface_portal.yml
    with:
      workingDirectory: ${{ needs.variables_workaround.outputs.workingDirectory }}
      NG_ENV_NAME: 'staging'
      NG_URL_121_SERVICE_API: 'https://staging.121.global/121-service/api'
      NG_AI_IKEY: ''
      NG_AI_ENDPOINT: ''
      APPLICATIONINSIGHTS_CONNECTION_STRING: ''

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment: 'test'
    steps:
      - name: Deploy to Azure Static Web App
        id: deploy_to_aswa
        uses: Azure/static-web-apps-deploy@v1
        with:
          skip_deploy_on_missing_secrets: true
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_ROCK_0411D2003 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          config_file_location: '${{ env.workingDirectory }}/'
          app_location: '${{ env.workingDirectory }}/www'
          output_location: ''
          skip_app_build: true
          skip_api_build: true
          deployment_environment: 'staging'

      - name: Finish
        run: |
          echo "Build version: ${{ needs.build.outputs.build_version }}" >> $GITHUB_STEP_SUMMARY
          echo "Preview: <${{ steps.deploy_to_aswa.outputs.static_web_app_url }}>" >> $GITHUB_STEP_SUMMARY
