# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: 'Deploy [NLRC] All'

permissions:
  actions: read

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy_service:
    name: 'Build + Deploy: 121-Service'
    uses: ./.github/workflows/deploy_client-nlrc_service.yml
    secrets:
      AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

  deploy_portal:
    needs: deploy_service
    name: 'Build + Deploy: Portal'
    uses: ./.github/workflows/deploy_client-nlrc_portal.yml
    secrets:
      AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_SKY_0413C1B03: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_SKY_0413C1B03 }}

  deploy_register:
    needs: deploy_service
    name: 'Build + Deploy: Register (PA)'
    uses: ./.github/workflows/deploy_client-nlrc_register.yml
    secrets:
      AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_POND_0B5AF0903: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_POND_0B5AF0903 }}
