# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: 'Deploy [staging] All'

permissions:
  actions: read
  pull-requests: write

on:
  workflow_call:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy_portal:
    name: 'Build + Deploy: Portal'
    uses: ./.github/workflows/deploy_staging_portal.yml
    secrets:
      AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_ROCK_0411D2003: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_ROCK_0411D2003 }}

  deploy_register:
    name: 'Build + Deploy: Register (PA)'
    uses: ./.github/workflows/deploy_staging_register.yml
    secrets:
      AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_BAY_0AF9ABD03: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_BAY_0AF9ABD03 }}

  deploy_verify:
    name: 'Build + Deploy: Verify (AW)'
    uses: ./.github/workflows/deploy_staging_verify.yml
    secrets:
      AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_SAND_08D7E2903: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_SAND_08D7E2903 }}

  deploy_service:
    name: 'Build + Deploy: 121-Service'
    uses: ./.github/workflows/deploy_staging_service.yml
    secrets:
      AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
