# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: 'Deploy [dorcas-ethiopia] Interface: Portal'

env:
  workingDirectory: interfaces/HO-Portal

permissions:
  actions: read
  pull-requests: write

on:
  workflow_call:
    secrets:
      AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_CLIFF_065742603:
        required: true
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build and Deploy Job
    runs-on: ubuntu-latest
    environment: 'client-dorcas-ethiopia'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name: Add environment-specific icon
      #   working-directory: ${{ env.workingDirectory }}
      #   run: |
      #     echo "" | base64 --decode > src/favicon.dorcas-ethiopia.ico
      #     cp --force src/favicon.dorcas-ethiopia.ico src/favicon.ico

      - name: Build Interface
        id: build
        uses: ./.github/actions/build-interface
        with:
          interfacePath: ${{ env.workingDirectory }}
        env:
          NG_ENV_NAME: ''
          NG_URL_121_SERVICE_API: 'https://dorcas-ethiopia.121.global/api'
          NG_AI_IKEY: ''
          NG_AI_ENDPOINT: ''
          APPLICATIONINSIGHTS_CONNECTION_STRING: ''

      # More information on Static Web App workflow configurations,
      # See: https://aka.ms/swaworkflowconfig
      - name: Deploy to Azure Static Web App
        id: deploy_to_aswa
        uses: Azure/static-web-apps-deploy@v1
        with:
          skip_deploy_on_missing_secrets: true
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_CLIFF_065742603 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          config_file_location: '${{ env.workingDirectory }}/'
          app_location: '${{ env.workingDirectory }}/www'
          output_location: ''
          skip_app_build: true
          skip_api_build: true

      - name: Finish
        run: |
          echo "Build version: ${{ steps.build.outputs.build_version }}" >> $GITHUB_STEP_SUMMARY
          echo "Preview: <${{ steps.deploy_to_aswa.outputs.static_web_app_url }}>" >> $GITHUB_STEP_SUMMARY
