# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: 'Deploy [jrethiopia] All'

permissions:
  actions: read

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy_service:
    name: 'Build + Deploy: 121-Service'
    uses: ./.github/workflows/deploy_client-jrethiopia_service.yml
    secrets:
      AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

  deploy_portal:
    needs: deploy_service
    name: 'Build + Deploy: Portal'
    uses: ./.github/workflows/deploy_client-jrethiopia_portal.yml
    secrets:
      AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_CLIFF_065742603: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_CLIFF_065742603 }}

  deploy_register:
    needs: deploy_service
    name: 'Build + Deploy: Register (PA)'
    uses: ./.github/workflows/deploy_client-jrethiopia_register.yml
    secrets:
      AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_FOREST_03195DB03: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_FOREST_03195DB03 }}
