# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: 'Test Service: Code'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/test_service_code.yml'
      - 'services/121-service/**'

env:
  workingDirectory: 'services/121-service/'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version-file: '${{ env.workingDirectory }}/.node-version'
          cache: 'npm'
          cache-dependency-path: '${{ env.workingDirectory }}/package-lock.json'

      - name: Install
        working-directory: ${{ env.workingDirectory }}
        run: 'npm ci --omit=optional --no-fund --no-audit'

      - name: Lint
        working-directory: ${{ env.workingDirectory }}
        run: 'npm run lint'
