# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: 'Test Workflows'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Lint
        uses: raven-actions/actionlint@v1
